[theme]
base = "light"
primaryColor = "#1e40af"
backgroundColor = "#f1f5f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"

[server]
headless = true
runOnSave = true

[client]
toolbarMode = "minimal"
showErrorDetails = false

[browser]
gatherUsageStats = false